02_Address_Book/config/routes.rb
Rails.application.routes.draw do

get '/contacts', to: 'contacts#index'
get '/contacts/new', to: 'contacts#new', as: :new_contact
post '/contacts', to: 'contacts#create'
post '/contacts/make_favorite', to: 'contacts#make_favorite'
post '/contacts/unfavorite', to: 'contacts#unfavorite'
get '/contacts/:id', to: 'contacts#show', as: :contact
get '/filter', to: 'contacts#filter'

end

02_Address_Book/app/models/contact.rb
class Contact < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

02_Address_Book/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

02_Address_Book/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.order(created_at: :desc)
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def filter
    search_term = params[:search]
    @contacts_searched = Contact.where("name LIKE ?", "#{search_term}%")
    render 'search'
  end

  def create
    contact = Contact.new(contact_params)
    contact.save
    redirect_to '/contacts'
  end

  def make_favorite
    contact = Contact.find(params[:id])
    contact.update_attributes(favorite: true)
    redirect_to '/contacts'
  end

  def unfavorite
    contact = Contact.find(params[:id])
    contact.update_attributes(favorite: false)
    redirect_to '/contacts'
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :address, :phone_number, :email, :avatar)
  end
end

02_Address_Book/app/helpers/application_helper.rb
module ApplicationHelper
end

02_Address_Book/app/helpers/contacts_helper.rb
module ContactsHelper
end

02_Address_Book/app/views/contacts/index.html.erb
<h4>All our contacts:</h4>
<ul>
  <% @contacts.each do |contact| %>
    <li> <%= link_to contact.name, contact_path(contact) %> </li>
  <% end %>
</ul>

<h4>Search Contact:</h4>

<form action="/filter" method="">
  <input type="text" name="contact[:search]">
  <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
  <input type="submit">
  <!-- search_field(:user, :name, autosave: false) -->
</form>
<%= link_to 'Add a new contact', new_contact_path %>

02_Address_Book/app/views/contacts/new.html.erb
<h4>Add a new contact:</h4>

<div class="add-format">
  <%= form_for @contact, html: { multipart: true } do |f| %>
    <div class="">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="">
    <%= f.file_field :avatar %>
    </div>
    <div class="">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
      <div class="">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number %>
      </div>
      <div class="">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>

        <%= f.submit :Save %>
  <% end %>
</div>

02_Address_Book/app/views/contacts/search.html.erb
<h4>Your search results</h4>
<ul>
  <% @contacts_searched.each do |contact| %>
  <li> <%= link_to contact.name, contact_path(contact) %> </li>
  <% end %>
</ul>

02_Address_Book/app/views/contacts/show.html.erb
<h4>Contact info:</h4>
<p>Name: <%= @contact.name %> </p>
<p>Address: <%= @contact.address %> </p>
<p>Phone Number: <%= @contact.phone_number %> </p>
<p>Email: <%= @contact.email %> </p>
<% if @contact.avatar.url %>
  <%= image_tag @contact.avatar.url %>
<% end %>

<% if @contact.favorite %>
<h4>Unfavorite contact:</h4>
<%= form_tag("/contacts/unfavorite", method: "post") do %>
  <%= hidden_field_tag :id,  "#{@contact.id}" %>
  <%= submit_tag :Unfavorite %>
  <% end %>
<% else %>
<h4>Add as favorite:</h4>
  <%= form_tag("/contacts/make_favorite", method: "post") do %>
    <%= hidden_field_tag :id,  "#{@contact.id}" %>
    <%= submit_tag :Favorite %>
  <% end %>
<% end %>

02_Address_Book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>