03_Auctions_Site/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get '/', to: 'users#form_login'
  # post '/', to: 'users#login'

  # get '/users/new', to: 'users#new'
  get '/users/:id', to: 'users#show', as: :user_show
  # post '/users', to: 'users#create'
  # delete '/users/:id', to: 'users#destroy', as: :users_destroy

  get '/users/:user_id/products', to: 'products#index'
  get '/users/:user_id/products/new', to: 'products#new',
    as: :user_products_new
  get '/users/:user_id/products/:id', to: 'products#show',
    as: :user_products_show
  post '/users/:user_id/products',
    to: 'products#create', as: :user_products
  delete '/users/:user_id/products/:id',
    to: 'products#destroy', as: :user_products_destroy

  post '/products/:product_id/bids', to: 'bids#create'
  post '/products/:product_id/buynow', to: 'products#buynow'

  resources :reviews, only: [:create, :edit, :update, :destroy]

  get '/api/users/:user_id/seller_reviews', to: 'seller_reviews#show'
end

03_Auctions_Site/app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

03_Auctions_Site/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :bids, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def show_winner
    bid_winner = bids.max {|a,b| a.amount <=> b.amount }
    (bid_winner) ? bid_winner.user.name : "None"
  end

  def get_max_bid
    max_bid = bids.max{|a,b| a.amount <=> b.amount }
    max_bid ? max_bid.amount : 0
  end
end

03_Auctions_Site/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

03_Auctions_Site/app/models/seller_review.rb
class SellerReview < ActiveRecord::Base
  belongs_to :subject, class_name: :User
  belongs_to :author, class_name: :User
end

03_Auctions_Site/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :products, dependent: :destroy
	has_many :bids, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :seller_reviews, class_name: :SellerReview, foreign_key: :user_id, dependent: :destroy

	validates :email, presence: true, uniqueness: true
end

03_Auctions_Site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

03_Auctions_Site/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def create
    amount = params[:bid][:amount].to_i
    @user = User.find_by(email: params[:bid][:email])
    unless @user
      render :no_users_found
    end
    @product = Product.find_by(id: params[:product_id])
    if amount > @product.minimum_bid &&
        amount > @product.get_max_bid &&
        @product.user.id != @user.id
      @bid = @product.bids.new(
        amount: params[:bid][:amount],
        user_id: @user.id)
      @bid.save
    end
    redirect_to user_products_show_path(@product.user.id, @product.id)
  end
end

03_Auctions_Site/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id])
    unless @user
      render :no_users_found
    end
    @products = @user.products
  end

  def show
    @user = User.find_by(id: params[:user_id])
    unless @user
      render :no_users_found
    end
    @product = @user.products.find_by(id: params[:id])
    @bids = @product.bids
  end

  def new
    @user = User.find_by(id: params[:user_id])
    unless @user
      render :no_users_found
    end
    @product = @user.products.new
  end

  def create
    @user = User.find_by(id: params[:user_id])
    unless @user
      render :no_users_found
    end
    @product = @user.products.new(
      title: params[:product][:title],
      description: params[:product][:description],
      deadline: params[:product][:deadline],
      minimum_bid: params[:product][:minimum_bid],
      buy_now: params[:product][:buy_now])
    if @product.save
      redirect_to user_products_path(@user.id)
    else
      render "new"
    end
  end

  def destroy
    user = User.find_by(id: params[:user_id])
    unless user
      render :no_users_found
    end
    product = user.products.find_by(id: params[:id])
    product.destroy
    redirect_to user_products_path(user.id)
  end

  def buynow
    product = Product.find_by(id: params[:product_id])
    product.deadline = Time.now
    product.save
    amount = product.get_max_bid + 1
    bid = product.bids.new(
        amount: amount,
        user_id: current_user.id)
    bid.save
    redirect_to user_products_show_path(product.user.id, product.id)
  end
end

03_Auctions_Site/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(
      description: params[:review][:description],
      user_id: params[:review][:user_id],
      product_id: params[:review][:product_id])
    @review.save
    redirect_to user_products_show_path(params[:review][:user_id], params[:review][:product_id])
  end

  def edit
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @review = Review.find(params[:id])
  end

  def update
    binding.pry
    review = Review.find(params[:id])
    unless current_user.id == review.user.id
      respond_to do |format|
        format.html { redirect_to reviews, notice: 'You dont have permission to edit this review.' }
      end
    end
    review.description = params[:review][:description]
    review.save
    redirect_to reviews
  end
end

03_Auctions_Site/app/controllers/seller_reviews_controller.rb
class SellerReviewsController < ApplicationController
  def show
    seller_reviews = SellerReview.where(subject_id: params[:user_id])
    render json: seller_reviews
  end
end

03_Auctions_Site/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    @seller_reviews = SellerReview.where(subject_id: params[:id])
    unless @user
      render :no_users_found
    end
  end

  def index
  end
  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(
  #     name: params[:user][:name],
  #     email: params[:user][:email],
  #     password: params[:user][:password])
  #   if @user.save
  #     redirect_to "/"
  #   else
  #     redirect_to "/users/new"
  #   end
  # end

  # def destroy
  #   user = User.find_by(id: params[:id])
  #   unless user
  #     render :no_users_found
  #   end
  #   user.destroy
  #   redirect_to "/users/new"
  # end

  # def form_login
  # end

  # def login
  #   user = User.find_by(email: params[:user][:email])
  #   unless user
  #     redirect_to "/"
  #   end
  #   if user.password == params[:user][:password]
  #     session[:user_id] = user.id
  #     redirect_to user_show_path(user.id)
  #   else
  #     redirect_to "/"
  #   end
  # end
end

03_Auctions_Site/app/helpers/application_helper.rb
module ApplicationHelper
end

03_Auctions_Site/app/helpers/bids_helper.rb
module BidsHelper
end

03_Auctions_Site/app/helpers/products_helper.rb
module ProductsHelper
end

03_Auctions_Site/app/helpers/reviews_helper.rb
module ReviewsHelper
end

03_Auctions_Site/app/helpers/seller_reviews_helper.rb
module SellerReviewsHelper
end

03_Auctions_Site/app/helpers/users_helper.rb
module UsersHelper
  def seller_reviews_average(seller_reviews)
    total = seller_reviews.reduce(0) do |result, review|
      result += review.rating
    end
    if seller_reviews.length != 0
      total / seller_reviews.length
    else
      0
    end
  end
end

03_Auctions_Site/app/views/bids/no_users_found.html.erb
<h1>Erroraco</h1>
<h2>This user not exist</h2>

03_Auctions_Site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionsSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="top_bar">
    <% if user_signed_in? %>
      <p><%= link_to 'Sign out', destroy_user_session_path, method: 'DELETE' %></p>
    <% else %>
      <p>
        <%= link_to 'Sign_up', new_user_registration_path %> | 
        <%= link_to 'Sign_in', new_user_session_path %>
      </p>
    <% end %>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

03_Auctions_Site/app/views/products/index.html.erb
<h1><%= @user.name %></h1>

<ul>
	<% @products.each do |product| %>
		<li><%= link_to product.title, user_products_show_path(@user.id, product.id) %></li>
	<% end %>
</ul>

<%= link_to "New product", user_products_new_path(@user.id) %>

03_Auctions_Site/app/views/products/new.html.erb
<h1>Add a new product</h1>
<%= form_for [@user, @product] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.label :deadline %>
	<%= f.date_field :deadline %>

	<%= f.label :minimum_bid %>
	<%= f.number_field :minimum_bid %>

  <%= f.label :buy_now %>
  <%= f.number_field :buy_now %>

	<%= f.submit "Save" %>
<% end %>

03_Auctions_Site/app/views/products/no_users_found.html.erb
<h1>Erroraco</h1>
<h2>This user not exist</h2>

03_Auctions_Site/app/views/products/show.html.erb
<h1>Title: <%= @product.title %></h1>
<p>Description: <%= @product.description %></p>
<p>Deadline: <%= @product.deadline %></p>
<p>Minimum Bid: <%= @product.minimum_bid %>$</p>

<ul>
	<% @bids.each do |bid| %>
		<li>
			<div><%= bid.user.name %> - <%= bid.amount %>$</div>
		</li>
	<% end %>
</ul>
<% if @product.deadline > Time.now %>
	<form action="/products/<%= @product.id %>/bids" method="post">
		<input type="hidden" name="authenticity_token" value="or954jKEmRn3nUeAufYg5pG7KuFTnin/FvdrSRSSLHpBlKeiWALULG0FFHuBr2zUK/K7sd8s277UhiHWNEh7LQ==">
		<label for="bid_email">Email</label>
		<input type="email" name="bid[email]" id="bid_email">

		<label for="bid_amount">Amount</label>
		<input type="number" name="bid[amount]" id="bid_amount">

		<button type="submit">Bid</button>
	</form>
	<form action="/products/<%= @product.id %>/buynow" method="post">
		<input type="hidden" name="authenticity_token" value="or954jKEmRn3nUeAufYg5pG7KuFTnin/FvdrSRSSLHpBlKeiWALULG0FFHuBr2zUK/K7sd8s277UhiHWNEh7LQ==">
		<button type="submit">Buy now</button>
	</form>
<% else %>
	<p>The winner is: <%= @product.show_winner %></p>
	<% @product.reviews.each do |review| %>
		<li>
			<div><%= review.description %></div>
		</li>
	<% end %>
	<% if user_signed_in? %>
		<form action="/reviews" method="post">
			<input type="hidden" name="authenticity_token" value="or954jKEmRn3nUeAufYg5pG7KuFTnin/FvdrSRSSLHpBlKeiWALULG0FFHuBr2zUK/K7sd8s277UhiHWNEh7LQ==">
			<input type="hidden" name="review[user_id]" value="<%= @user.id %>">
			<input type="hidden" name="review[product_id]" value="<%= @product.id %>">
			<label for="review_description">Review Description</label>
			<textarea name="review[description]" id="review_description"></textarea>

			<button type="submit">Send</button>
		</form>
	<% end %>
<% end %>

<%= link_to "Products", user_products_path(@user.id) %>
<%= link_to "Delete", user_products_destroy_path(@user.id, @product.id), method: :delete, confirm: 'Are you sure?' %>

03_Auctions_Site/app/views/reviews/edit.html.erb
<%= form_for @review do |f| %>
  <%= f.label :description %>:
  <%= f.text_area :description %><br />
  
  <%= f.submit %>
<% end %>

03_Auctions_Site/app/views/users/form_login.html.erb
<form action="/" method="post">
	<input type="hidden" name="authenticity_token" value="or954jKEmRn3nUeAufYg5pG7KuFTnin/FvdrSRSSLHpBlKeiWALULG0FFHuBr2zUK/K7sd8s277UhiHWNEh7LQ==">
	<label for="email">Email</label>
	<input type="email" name="user[email]" id="email">

	<label for="password">Password</label>
	<input type="password" name="user[password]" id="password">

	<button type="submit">Login</button>
</form>

<%= link_to "Register", users_new_path %>

03_Auctions_Site/app/views/users/index.html.erb
<p>
   Hello Folks
</p>

03_Auctions_Site/app/views/users/new.html.erb
<h1>Add a project</h1>
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.button %>
<% end %>

03_Auctions_Site/app/views/users/no_users_found.html.erb
<h1>Erroraco</h1>
<h2>This user not exist</h2>

03_Auctions_Site/app/views/users/show.html.erb
<h1>User <%= @user.id %> description</h1>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

<p>Rating: <%= seller_reviews_average(@seller_reviews) %></p>

<ul>
  <% @seller_reviews.each do | seller_review | %>
    <li><%= seller_review.author.name %> - <%= seller_review.review_content %></li>
  <% end %>
</ul>